{
 "title": "Kubernetes / Networking / Connection / Namespace (Pods)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(container_network_tcp_usage_total, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_network_tcp_usage_total, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Established Connection",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod!=\"\", tcp_state=\"established\"}\n)",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod!=\"\", tcp_state=\"established\"}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Established Connections Per Pod",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=~\"$namespace\", pod!=\"\"}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}