{
 "title": "Kubernetes / Networking / Connection / Workload",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(container_network_tcp_usage_total, cluster)"
   },
   {
    "name": "namespace",
    "query": "label_values(container_network_tcp_usage_total, namespace)"
   },
   {
    "name": "workload",
    "query": "label_values(mixin_pod_workload{namespace=~\"$namespace\"}, workload)"
   },
   {
    "name": "type",
    "query": "label_values(mixin_pod_workload{namespace=~\"$namespace\", workload=~\"$workload\"}, workload_type)"
   }
  ]
 },
 "panels": [
  {
   "title": "Established Connections of Workload",
   "type": "graph",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod!=\"\", tcp_state=\"established\"}\n  * on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{cluster=~\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (workload)",
     "legendFormat": "{{ workload }}"
    }
   ]
  },
  {
   "title": "Connections Per State of Workload",
   "type": "graph",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod!=\"\"}\n  * on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{cluster=~\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (tcp_state)",
     "legendFormat": "{{ tcp_state }}"
    }
   ]
  },
  { "title": "TCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Current Established Connections Per Pod",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod!=\"\", tcp_state=\"established\"}\n  * on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{cluster=~\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Established Connections Per Pod History",
   "type": "graph",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  container_network_tcp_usage_total{cluster=~\"$cluster\", namespace=\"$namespace\", pod!=\"\", tcp_state=\"established\"}\n  * on(namespace,pod)\n  group_left(workload, workload_type) mixin_pod_workload{cluster=~\"$cluster\", namespace=\"$namespace\", workload=\"$workload\", workload_type=\"$type\"}\n) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  }
 ]
}