- job_name: cadvisor
  honor_labels: false
  kubernetes_sd_configs:
  - role: endpoints
    namespaces:
      names:
      - cadvisor
  scheme: http
  relabel_configs:
  - action: keep
    source_labels:
    - __meta_kubernetes_service_label_name
    regex: cadvisor
  - action: keep
    source_labels:
    - __meta_kubernetes_endpoint_port_name
    regex: http
  - source_labels:
    - __meta_kubernetes_endpoint_node_name
    target_label: node
    replacement: ${1}
  metric_relabel_configs:
  - source_labels: [ __name__ ]
    regex: 'container_network_tcp_usage_total|container_network_tcp6_usage_total'
    action: keep
  - source_labels: [container_label_io_kubernetes_pod_name]
    target_label: pod
  - source_labels: [container_label_io_kubernetes_pod_namespace]
    target_label: namespace
  - regex: "container_label_io_kubernetes_pod_name|container_label_io_kubernetes_pod_namespace"
    action: labeldrop